name: Sample-App

on:
  push:
    paths:
      - "*/**"
  pull_request:
    paths:
      - "*/**"

jobs:
  api-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Create network for linkage to lms
        run: docker network create sample_app_default
      - name: Docker compose up
        run: docker-compose -f docker-compose-workflow.yml up -d web db
      - name: Setup and Run test
        run: docker-compose -f docker-compose-workflow.yml exec -T web bash -c "rails test"